### ISSUE TITLE
Unable to run the Webservices UI on WSL

### ISSUE THREAD

**Issue by KunalGehlot** [udacity/nd131-openvino-fundamentals-project-starter#3]
I completed all the previous steps mentioned in the instructions. Though during installing npm, I had to downgrade Nodejs as suggested by the command `sudo aptitude install npm` (I was unable to install npm any other way) and then I installed `nodejs-legacy`, again using aptitude to make sure to not to disturb any packages.

After that, I was successfully able to Start the Mosca server but encountered this error during running `npm install` under `/webservices/ui` 

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.12

and if I try to run `npm run dev`, I get

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
> 2 info using npm@3.5.2
> 3 info using node@v4.2.6
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle intel-people-counter-app@0.1.0-predev: intel-people-counter-app@0.1.0
> 6 silly lifecycle intel-people-counter-app@0.1.0-predev: no script for predev, continuing
> 7 info lifecycle intel-people-counter-app@0.1.0-dev: intel-people-counter-app@0.1.0
> 8 verbose lifecycle intel-people-counter-app@0.1.0-dev: unsafe-perm in lifecycle true
> 9 verbose lifecycle intel-people-counter-app@0.1.0-dev: PATH: /usr/share/npm/bin/node-gyp-bin:/home/zack/nd131-openvino-fundamentals-project-starter/webservice/ui/node_modules/.bin:/home/zack/bin:/home/zack/.local/bin:/opt/intel/openvino_2020.1.023/deployment_tools/model_optimizer:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/Brackets/command:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/Gehlo/AppData/Local/Programs/Python/Python36/Scripts/:/mnt/c/Users/Gehlo/AppData/Local/Programs/Python/Python36/:/mnt/c/Users/Gehlo/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Gehlo/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Gehlo/AppData/Local/GitHubDesktop/bin:/snap/bin
> 10 verbose lifecycle intel-people-counter-app@0.1.0-dev: CWD: /home/zack/nd131-openvino-fundamentals-project-starter/webservice/ui
> 11 silly lifecycle intel-people-counter-app@0.1.0-dev: Args: [ '-c',
> 11 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --history-api-fallback --watch --hot --inline' ]
> 12 silly lifecycle intel-people-counter-app@0.1.0-dev: Returned: code: 1  signal: null
> 13 info lifecycle intel-people-counter-app@0.1.0-dev: Failed to exec dev script
> 14 verbose stack Error: intel-people-counter-app@0.1.0 dev: `cross-env NODE_ENV=development webpack-dev-server --history-api-fallback --watch --hot --inline`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at EventEmitter.emit (events.js:172:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
> 14 verbose stack     at emitTwo (events.js:87:13)
> 14 verbose stack     at ChildProcess.emit (events.js:172:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:821:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 15 verbose pkgid intel-people-counter-app@0.1.0
> 16 verbose cwd /home/zack/nd131-openvino-fundamentals-project-starter/webservice/ui
> 17 error Linux 4.4.0-19041-Microsoft
> 18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
> 19 error node v4.2.6
> 20 error npm  v3.5.2
> 21 error code ELIFECYCLE
> 22 error intel-people-counter-app@0.1.0 dev: `cross-env NODE_ENV=development webpack-dev-server --history-api-fallback --watch --hot --inline`
> 22 error Exit status 1
> 23 error Failed at the intel-people-counter-app@0.1.0 dev script 'cross-env NODE_ENV=development webpack-dev-server --history-api-fallback --watch --hot --inline'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the intel-people-counter-app package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     cross-env NODE_ENV=development webpack-dev-server --history-api-fallback --watch --hot --inline
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs intel-people-counter-app
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls intel-people-counter-app
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by KunalGehlot** [comment]
It turns out it works fine with Ubuntu 18.04

**Comment by KunalGehlot** [comment]
It turns out it works fine with Ubuntu 18.04
